//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace ABCOnlineEmployeeProjectAssignment.Models
{
    using System;
    using System.Collections.Generic;
    
    public partial class ProjectAssignment
    {
        public int ProjectAssignmentId { get; set; }
        public int EmployeeNumber { get; set; }
        public string ProjectCode { get; set; }
        public System.DateTime AssignedDate { get; set; }
        public Nullable<System.DateTime> SubmittedDate { get; set; }
    
        public virtual Employee Employee { get; set; }
        public virtual Project Project { get; set; }
    }
}
